name: vcpkg-action
description: Simple action to run vcpkg and cache results
inputs:
  pkgs:
    description: "List of packages to build, separated by spaces. Cannot be used with manifest-dir"
    required: false
  triplet:
    description: "vcpkg triplet to use"
    required: true
  extra-args:
    description: "Extra vcpkg install command line args (optional)"
    required: false
    default: ''
  cache-key:
    description: "Additional cache key component (optional)"
    required: false
  disable-cache:
    description: "Disable cache (useful for release builds)"
    required: false
    default: 'false'
  revision:
    description: "vcpkg revision to checkout."
    required: false
    default: ''
  token:
    description: "GitHub token to authenticate API requests. Recommended to use  github.token "
    required: false
    default: ''
  manifest-dir:
    description: Directory containing vcpkg.json manifest file. Cannot be used with pkgs.
    required: false
    default: ''
  github-binarycache:
    description: "Use vcpkg built-in GitHub binary caching. If not specified, will use the dry-run based file cache."
    required: false
    default: ''
  fetch-depth:
    description: "Fetch depth for vcpkg checkout"
    required: false
    default: "1"
  vcpkg-subdir:
    description: "The subdirectory into which to install VCPKG"
    required: false
    default: "vcpkg"

outputs:
  vcpkg-cmake-config:
    description: Configure options for cmake to use vcpkg
    value: ${{ steps.vcpkg-cmake-config.outputs.vcpkg-cmake-config }}
  vcpkg-cache-hash:
    description: Hash of the vcpkg cache key
    value: ${{ steps.vcpkg-cmake-config.outputs.vcpkg-cache-hash }}
runs:
  using: "composite"
  steps:
  - name: Get latest Github release
    uses: cardinalby/git-get-release-action@v1
    id: get-latest-vcpkg-release
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
    with:
      latest: true
      repo: microsoft/vcpkg
      prerelease: false
      draft: false    
  - name: Determine checkout tag
    shell: bash
    id: determine-checkout-revision
    run: |
      if [[ "${{ inputs.revision }}" != "" ]]; then
        echo "vcpkg-revision=${{ inputs.revision }}" >> $GITHUB_OUTPUT
      else
        echo "vcpkg-revision=${{ steps.get-latest-vcpkg-release.outputs.tag_name }}" >> $GITHUB_OUTPUT
      fi
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: checkout-vcpkg
    uses: actions/checkout@v4
    with:
      path: ${{ github.workspace }}/${{ inputs.vcpkg-subdir }}
      repository: microsoft/vcpkg
      ref: '${{ steps.determine-checkout-revision.outputs.vcpkg-revision }}'
      fetch-depth: ${{ inputs.fetch-depth }}
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: bootstrap-vcpkg-win
    if: runner.os == 'Windows'
    working-directory: ${{ github.workspace }}\${{ inputs.vcpkg-subdir }}
    run: bootstrap-vcpkg.bat
    shell: cmd
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: bootstrap-vcpkg-unix
    if: runner.os != 'Windows'
    working-directory: ${{ github.workspace }}/${{ inputs.vcpkg-subdir }}
    run: ./bootstrap-vcpkg.sh
    shell: bash
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: set-binarycache-variable
    if: inputs.github-binarycache != 'true' && inputs.github-binarycache != true
    shell: bash
    run: |
      echo VCPKG_DEFAULT_BINARY_CACHE='${{ github.workspace }}/vcpkg_cache' >> $GITHUB_ENV
      mkdir -p '${{ github.workspace }}/vcpkg_cache'
  - name: vcpkg-dry-run-win
    if: runner.os == 'Windows' && inputs.manifest-dir == '' && inputs.github-binarycache != 'true' && inputs.github-binarycache != true
    working-directory: ${{ github.workspace }}\${{ inputs.vcpkg-subdir }}
    shell: powershell
    run: |
      & "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/vcpkg.exe" install --dry-run --triplet ${{ inputs.triplet }} ${{ inputs.extra-args }} ${{ inputs.pkgs }} | Tee-Object -FilePath vcpkg_dry_run.txt
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: vcpkg-dry-run-unix
    if: runner.os != 'Windows' && inputs.manifest-dir == '' && inputs.github-binarycache != 'true' && inputs.github-binarycache != true
    working-directory: ${{ github.workspace }}/${{ inputs.vcpkg-subdir }}
    shell: bash
    run: |
      "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/vcpkg" install --dry-run --triplet ${{ inputs.triplet }} ${{ inputs.extra-args }} ${{ inputs.pkgs }} | tee vcpkg_dry_run.txt
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: vcpkg-dry-run-win-manifest
    if: runner.os == 'Windows' && inputs.manifest-dir != '' && inputs.github-binarycache != 'true' && inputs.github-binarycache != true
    working-directory: ${{ github.workspace }}\${{ inputs.vcpkg-subdir }}
    shell: powershell
    run: |
      & "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/vcpkg.exe" install --dry-run --triplet ${{ inputs.triplet }} ${{ inputs.extra-args }} --x-manifest-root=${{ inputs.manifest-dir }} --x-install-root=${{ github.workspace }}\${{ inputs.vcpkg-subdir }}\installed | Tee-Object -FilePath vcpkg_dry_run.txt
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: vcpkg-dry-run-unix-manifest
    if: runner.os != 'Windows' && inputs.manifest-dir != '' && inputs.github-binarycache != 'true' && inputs.github-binarycache != true
    working-directory: ${{ github.workspace }}/${{ inputs.vcpkg-subdir }}
    shell: bash
    run: |
      "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/vcpkg" install --dry-run --triplet ${{ inputs.triplet }} ${{ inputs.extra-args }} --x-manifest-root=${{ inputs.manifest-dir }} --x-install-root=${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/installed | tee vcpkg_dry_run.txt
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: cache-vcpkg-archives
    if: ${{ inputs.disable_cache != 'true' }} && inputs.github-binarycache != 'true' && inputs.github-binarycache != true
    id: cache-vcpkg-archives
    uses: pat-s/always-upload-cache@v3
    with:
      path: ${{ github.workspace }}/vcpkg_cache
      key: ${{ runner.os }}-${{ inputs.triplet }}-vcpkg-${{ hashFiles('${{ inputs.vcpkg-subdir }}/vcpkg_dry_run.txt') }}-${{ inputs.cache-key }}
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: Export GitHub Actions cache environment variables
    if: (inputs.disable_cache != 'true' && inputs.disable_cache != true) &&  (inputs.github-binarycache == 'true' || inputs.github-binarycache == true)
    uses: actions/github-script@v6
    with:
      script: |
        core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
        core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
        core.exportVariable('VCPKG_BINARY_SOURCES', "clear;x-gha,readwrite");
  - name: build-vcpkg-win
    if: runner.os == 'Windows' && inputs.manifest-dir == ''
    shell: cmd
    working-directory: ${{ github.workspace }}\${{ inputs.vcpkg-subdir }}
    run: |
      "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/vcpkg.exe" install --triplet ${{ inputs.triplet }} ${{ inputs.extra-args }} ${{ inputs.pkgs }}
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: build-vcpkg-unix
    if: runner.os != 'Windows' && inputs.manifest-dir == ''
    shell: bash
    working-directory: ${{ github.workspace }}/${{ inputs.vcpkg-subdir }}
    run: |
      "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/vcpkg" install --triplet ${{ inputs.triplet }} ${{ inputs.extra-args }} ${{ inputs.pkgs }}
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: build-vcpkg-win
    if: runner.os == 'Windows' && inputs.manifest-dir != ''
    shell: cmd
    working-directory: ${{ github.workspace }}\${{ inputs.vcpkg-subdir }}
    run: |
      "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/vcpkg.exe" install --triplet ${{ inputs.triplet }} ${{ inputs.extra-args }} --x-manifest-root=${{ inputs.manifest-dir }} --x-install-root=${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/installed
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: build-vcpkg-unix
    if: runner.os != 'Windows' && inputs.manifest-dir != ''
    shell: bash
    working-directory: ${{ github.workspace }}/${{ inputs.vcpkg-subdir }}
    run: |
      "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/vcpkg" install --triplet ${{ inputs.triplet }} ${{ inputs.extra-args }} --x-manifest-root=${{ inputs.manifest-dir }} --x-install-root=${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/installed
    env:
      VCPKG_ROOT: "${{ github.workspace }}/${{ inputs.vcpkg-subdir }}"
  - name: vcpkg cmake configure 
    shell: bash
    id: vcpkg-cmake-config
    run: |
      echo "vcpkg-cmake-config=-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/${{ inputs.vcpkg-subdir }}/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ inputs.triplet }} -DVCPKG_MANIFEST_MODE=OFF" >> $GITHUB_OUTPUT
      echo "vcpkg-cache-hash=${{ hashFiles('${{ inputs.vcpkg-subdir }}/vcpkg_dry_run.txt') }}-${{ inputs.cache-key }}" >> $GITHUB_OUTPUT
