name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: test-vcpkg-action
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-22.04
          vcpkg_triplet: x64-linux-release
          github-binarycache: false
        - os: macos-13
          vcpkg_triplet: x64-osx-release
          github-binarycache: false
        - os: windows-2022
          vcpkg_triplet: x64-windows-release
          github-binarycache: false
        - os: ubuntu-22.04
          vcpkg_triplet: x64-linux-release
          github-binarycache: true
        - os: macos-13
          vcpkg_triplet: x64-osx-release
          github-binarycache: true
        - os: windows-2022
          vcpkg_triplet: x64-windows-release
          github-binarycache: true
    steps:
      - uses: actions/checkout@v4
      - name: vcpkg build
        id: vcpkg
        uses: ./
        with:
          pkgs: boost-date-time
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: ${{ matrix.config.github-binarycache }}
      - name: tree
        if: runner.os == 'Windows'
        shell: cmd
        run: tree
      - name: cmake configure
        run: >
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -S ${{ github.workspace }}/.github/cmake_test -B cmake_build 

  test-latest-vcpkg-release:
    runs-on: ${{ matrix.config.os }}
    name: test-vcpkg-action-latest-vcpkg-release
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-22.04
          vcpkg_triplet: x64-linux-release
          github-binarycache: false
        - os: macos-13
          vcpkg_triplet: x64-osx-release
          github-binarycache: false
        - os: windows-2022
          vcpkg_triplet: x64-windows-release
          github-binarycache: false
        - os: ubuntu-22.04
          vcpkg_triplet: x64-linux-release
          github-binarycache: true
        - os: macos-13
          vcpkg_triplet: x64-osx-release
          github-binarycache: true
        - os: windows-2022
          vcpkg_triplet: x64-windows-release
          github-binarycache: true
    steps:
      - uses: actions/checkout@v4
      - name: vcpkg build
        id: vcpkg
        uses: ./
        with:
          pkgs: boost-date-time
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          token: ${{ github.token }}
          github-binarycache: ${{ matrix.config.github-binarycache }}
      - name: tree
        if: runner.os == 'Windows'
        shell: cmd
        run: tree
      - name: cmake configure
        run: >
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -S ${{ github.workspace }}/.github/cmake_test -B cmake_build 

  test-manifest:
    runs-on: ${{ matrix.config.os }}
    name: test-manifest
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-22.04
          vcpkg_triplet: x64-linux-release
          github-binarycache: false
        - os: macos-13
          vcpkg_triplet: x64-osx-release
          github-binarycache: false
        - os: windows-2022
          vcpkg_triplet: x64-windows-release
          github-binarycache: false
        - os: ubuntu-22.04
          vcpkg_triplet: x64-linux-release
          github-binarycache: true
        - os: macos-13
          vcpkg_triplet: x64-osx-release
          github-binarycache: true
        - os: windows-2022
          vcpkg_triplet: x64-windows-release
          github-binarycache: true
    steps:
      - uses: actions/checkout@v4
      - name: vcpkg build
        id: vcpkg
        uses: ./
        with:
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          token: ${{ github.token }}
          manifest-dir: ${{ github.workspace }}/.github/manifest
          github-binarycache: ${{ matrix.config.github-binarycache }}
      - name: cmake configure
        run: >
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -S ${{ github.workspace }}/.github/cmake_test -B cmake_build